title: Arjun Anilkumar
email: your-email@purdue.edu
description: Mechanical Engineering Portfolio | Propulsion & Manufacturing
baseurl: "" # leave empty
url: "https://arjunanilkuma.github.io"

# Build settings
# theme: architect # A standard, clean starter theme
theme: minima # this one looks like apple lowkey kinda tough
# theme: cayman # 
# theme: slate #
plugins:
  - jekyll-feed

